name: localization_example
description: just an example project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^1.5.3
  get_it:
  stacked:
  zooper_flutter_localization:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/localizations/
